// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  batchSetting: string;
  batchSettingItem: string;
  batchSettingItemLabel: string;
  button: string;
}
export const cssExports: CssExports;
export default cssExports;
