// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bubble: string;
  img: string;
  item: string;
  title: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
