// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cardStatistic: string;
  cardStatisticWrapper: string;
  cardWrapper: string;
  titleDesc: string;
  titlePopover: string;
  titleWrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
