// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  orderRowHeader: string;
  orderRowItem: string;
  orderRowItemCell: string;
  orderRowWrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
