// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  recharge: string;
  sms: string;
  tips: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
