// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-form-item': string;
  'ant-row': string;
  'arrayGroup-btn__item': string;
  'form-field': string;
  'form-item': string;
  'form-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
