// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-sn-table': string;
  addOrderNumWrapper: string;
  'ant-table-wrapper': string;
  'array-table__field--container': string;
  mark: string;
  productListStyle: string;
  supplyCancelTips: string;
  tipsSize: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
