// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  center: string;
  img: string;
  swipper: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
