// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  chooseColor: string;
  icon: string;
  inputs: string;
  picker: string;
  rButton: string;
}
export const cssExports: CssExports;
export default cssExports;
