// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  achievement: string;
  bottomLine: string;
  checkboxItem: string;
  delDiv: string;
  iconImg: string;
  imgShow: string;
  labelColor: string;
  posterItem: string;
  recruitPoster: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
