// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  attributeItemName: string;
  attributeItemValues: string;
  itemWrapper: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
