// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  addCoupon: string;
  detail: string;
  input: string;
  items: string;
  mannal: string;
  radio: string;
  remark: string;
  requerdIcon: string;
  textWidth: string;
  title: string;
  titles: string;
}
export const cssExports: CssExports;
export default cssExports;
