// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  detail: string;
  divImg: string;
  imgShowAnimation: string;
  item: string;
  message: string;
  pic: string;
  title: string;
  top: string;
}
export const cssExports: CssExports;
export default cssExports;
