// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  aliPay: string;
  basicInformation: string;
  basicTable: string;
  customerInformation: string;
  defaultCard: string;
  distributions: string;
  frame: string;
  frameBox: string;
  grouopBuy: string;
  headerTable: string;
  isPass: string;
  marginTop: string;
  money: string;
  moneyBox: string;
  moneyBoxItem: string;
  otherCard: string;
  payPrice: string;
  payType: string;
  price: string;
  productInfoPopconfirm: string;
  productInformation: string;
  productInformationNotParentOrderTable: string;
  productInformationTable: string;
  productInformationTitleBox: string;
  productInformationTitleHeader: string;
  productInformationTitleOrderInfo: string;
  qrCode: string;
  sn: string;
  supplier: string;
  supplierNo: string;
  supplyButton: string;
  supplyOrderDetail: string;
  supplyPad: string;
  wxPay: string;
  wxPayRadio: string;
  aliPayRadio: string;
}
export const cssExports: CssExports;
export default cssExports;
