// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  features: string;
  image: string;
  item: string;
  viewWrapper: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
