// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  addButton: string;
  addHome: string;
  butPadding: string;
  collectProduct: string;
  hrefLink: string;
  middlePrice: string;
  percent: string;
  sellPrice: string;
  priceDiv: string;
  rightItem: string;
  showDis: string;
  submitChoose: string;
  supplyModal: string;
  title: string;
  supplyName: string;
  topItem: string;
}
export const cssExports: CssExports;
export default cssExports;
