// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  [x: string]: string | undefined;
  captchaImage: string;
  login: string;
  other: string;
  prefixIcon: string;
  radioGroup: string;
  submit: string;
}
export const cssExports: CssExports;
export default cssExports;
