// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  columnList: string;
  columnListItem: string;
  'columnListItem-text': string;
  columnListItemActive: string;
  columnListItemDisabled: string;
  columnSelect: string;
  columnWrapper: string;
  search: string;
}
export const cssExports: CssExports;
export default cssExports;
