// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  addProduct: string;
  icon: string;
  title: string;
  titleBg: string;
}
export const cssExports: CssExports;
export default cssExports;
