// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  content: string;
  delete: string;
  feat: string;
  imgBox: string;
  itemWrap: string;
  set: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
