// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  content: string;
  desc: string;
  header: string;
  lang: string;
  logo: string;
  title: string;
  top: string;
}
export const cssExports: CssExports;
export default cssExports;
