// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  addNavigation: string;
  leftImg: string;
  tablePad: string;
  title: string;
  titleBg: string;
}
export const cssExports: CssExports;
export default cssExports;
