// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'list-btn__item': string;
  'list-btn__wrapper': string;
  'list-item__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
