// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  account: string;
  action: string;
  avatar: string;
  dark: string;
  header: string;
  left: string;
  logo: string;
  menu: string;
  name: string;
  right: string;
  search: string;
  trigger: string;
  triggerSmall: string;
}
export const cssExports: CssExports;
export default cssExports;
