// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  scrollWrapper: string;
  searchBox: string;
  searchTreeWrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
