// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  couponListItem: string;
  couponListWrapper: string;
  discountInfoList: string;
  header: string;
  modalFormType: string;
  modalFormWrapper: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
