// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  relatedStore: string | undefined;
  storeAreas: string | undefined;
  andSoOn: string;
  areas: string;
  detail: string;
  imgs: string;
  leftSide: string;
  modify: string;
  preElement: string;
  project: string;
  roomTabs: string;
  showPic: string;
  title: string;
  titleLine: string;
}
export const cssExports: CssExports;
export default cssExports;
