// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'programa-detail': string;
  'programa-detail-btn': string;
  'programa-detail-table': string;
  'programa-detail__form': string;
  'programa-detail__hide': string;
  'programa-detail__preview': string;
  'programa-title-btn': string;
}
export const cssExports: CssExports;
export default cssExports;
